# Site settings
title: B/RGB
email: contact@brgb.com
description: 
url: "http://clients.lucasbittar.com/brgb/" # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "/brgb" # does not include hostname
